apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mynodecronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysamplenodeapp
            image: nodeconsoleapp:v1
          restartPolicy: OnFailure
