apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mynodecronjob2
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysamplenodeapp2
            image: nodeconsoleapp:v2
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid

